# Generated by Django 6.1.1 on 2026-09-14 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Xona Raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Xizmatda (Aktiv)')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Xona Turi')),
                ('description', models.TextField(verbose_name="Tavsif va Ta'rif")),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bir kecha narxi ($)')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name="Sig'imi (kishi)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Rasm')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Bepul Wi-Fi')),
                ('has_tv', models.BooleanField(default=True, verbose_name='Smart TV')),
                ('has_air_conditioner', models.BooleanField(default=True, verbose_name='Konditsioner')),
                ('has_breakfast', models.BooleanField(default=False, verbose_name='Shved stoli nonushta')),
            ],
            options={
                'verbose_name': 'Xona Turi',
                'verbose_name_plural': 'Xona Turlari',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Kelish sanasi')),
                ('check_out', models.DateField(verbose_name='Ketish sanasi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jami Summa ($)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan'), ('completed', 'Yakunlangan')], default='confirmed', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.roomtype', verbose_name='Xona Turi'),
        ),
    ]
