# Generated by Django 6.1.1 on 2026-09-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.Sh')),
                ('position', models.CharField(max_length=150, verbose_name='Lavozimi')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/admins/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administratorlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.Sh')),
                ('specialty', models.CharField(max_length=150, verbose_name='Mutaxassisligi')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/chefs/', verbose_name='Rasm')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Oshpaz',
                'verbose_name_plural': 'Oshpazlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Turkum nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Menyu Turkumi',
                'verbose_name_plural': 'Menyu Turkumlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Taom nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Rasm')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.menucategory', verbose_name='Turkum')),
            ],
            options={
                'verbose_name': 'Menyu Taomi',
                'verbose_name_plural': 'Menyu Taomlari',
            },
        ),
    ]
