# Generated by Django 6.1.1 on 2026-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_administrator_chef_menucategory_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('click', 'Click'), ('payme', 'Payme')], max_length=10, null=True, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('paid', "Oldindan to'lov qilingan"), ('failed', "To'lov amalga oshmadi")], default='unpaid', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='booking',
            name='prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Oldindan to'langan summa ($)"),
        ),
        migrations.AddField(
            model_name='booking',
            name='prepayment_percent',
            field=models.PositiveIntegerField(choices=[(30, '30%'), (50, '50%')], default=30, verbose_name="Oldindan to'lov foizi"),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID'),
        ),
    ]
