# Generated by Django 6.1.1 on 2026-09-19 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_payment_method_booking_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('preparing', 'Tayyorlanmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holati')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jami summa ($)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma vaqti')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='booking.booking', verbose_name='Bron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi (buyurtma paytida)')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.menuitem', verbose_name='Taom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.foodorder', verbose_name='Zakaz')),
            ],
            options={
                'verbose_name': 'Zakaz Taomi',
                'verbose_name_plural': 'Zakaz Taomlari',
            },
        ),
    ]
